# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np #import numpy python library with import command

2. Create a null vector of size 10 

In [4]:
arrnull = np.zeros((10)) # it create a null vector of size 10

In [5]:
arrnull

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [7]:
vector = np.arange(10, 50) # this command create a vector with values from 10 to 49

In [9]:
vector # executing variable for checking its stored values

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [10]:
vector.shape # command for find the shape of any array

(40,)

In [11]:
np.shape(vector) # 2nd procedure to find the shape of array.

(40,)

5. Print the type of the previous array in question 3

In [12]:
type(vector) # return the array type

numpy.ndarray

6. Print the numpy version and the configuration


In [13]:
print(np.__version__) # used for getting the version of numpy

1.18.1


7. Print the dimension of the array in question 3


In [14]:
vector.ndim # it gives us the dimention of the array

1

8. Create a boolean array with all the True values

In [15]:
np.full((3, 3), True, dtype=bool) # create a 3x3 numpy array of all the true's values

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [16]:
np.ones((3,3), dtype=bool) # 2nd procedure to creat the above same

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

9. Create a two dimensional array




In [28]:
TwoDarray =  np.arange(4).reshape(2,2) # create two dimentional array

In [29]:
TwoDarray

array([[0, 1],
       [2, 3]])

10. Create a three dimensional array



In [30]:
ThreeDarray =  np.arange(9).reshape(3,3) # create three wo dimentional array

In [32]:
ThreeDarray

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [34]:
vector = np.arange(9) # array of nine elements present init 
vector[::-1] #reverse the vector 

array([8, 7, 6, 5, 4, 3, 2, 1, 0])

12. Create a null vector of size 10 but the fifth value which is 1 

In [36]:
vector_null = np.zeros(10) # create the null vector of size 10
vector_null[4] = 1 # index 4 means fifth position equals to one as desired
vector_null 

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [37]:
matrix_identity = np.ones((3,3)) # create a 3x3 identity matrix
matrix_identity

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [39]:
arr = np.array([1, 2, 3, 4, 5], dtype=float) # convert the data type of int into float
arr

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [40]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
arr1 * arr2  # this command used to multiply the array 1 into 2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [42]:
arr_compare = (arr1 > arr2) #compare two array with each others and returns T/F values
arr_compare

array([[ True, False,  True],
       [False,  True, False]])

17. Extract all odd numbers from arr with values(0-9)

In [48]:
arr = np.arange(10) # create the array 
num_odd = arr[ arr % 2 != 0] # extract all odd numbers 
num_odd

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [49]:
arr = np.arange(10)      #create the array of 10 elements
arr[ arr % 2 != 0] = -1  #replace all odd numbers to -1 from previous array
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [50]:
arr = np.arange(10)      #create the array of 10 elements
arr[5:9] = 12            #replace the values of indexes of places 5 to 8 equals to 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [54]:
TwoDayArray = np.ones((5,5)) # print original array
TwoDayArray[1:-1,1:-1] = 0 # put 1's on the border and o inside the arraay
TwoDayArray

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [56]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
arr2d[1][1] = 12  # replace the number inside array from 5 to 12 which is locate at array position of 5X5
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [58]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0][0] = 64 # convert all the values of 1st array to 64
arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [61]:
array2d = np.arange(10).reshape(2,5) # this gives us 2-D array with 0-9 values
array2d[0] # slice out the first 1-D array from it.

array([0, 1, 2, 3, 4])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [64]:
array2d = np.arange(10).reshape(2,5) # this gives us 2-D array with 0-9 values
array2d
array2d[1][1] # slice out the second value from 2nd 2-D array from it.

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [65]:
array2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
array2d[:,2][0:2] # slice out the third column but only the first two rows

array([3, 6])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [66]:
ran_value_array = np.random.randn(100).reshape(10,10) # create 10X10 array with random values
ran_value_array

array([[-0.54519921, -1.30199171, -0.50393788, -0.96912572, -1.86775843,
        -0.7489276 , -0.26025054,  0.99164284, -1.1651186 , -0.00292185],
       [ 0.53136839,  0.69443934, -0.15402553,  0.65297189,  0.29447549,
         0.72396259,  1.03386333,  0.11414924,  0.66158981, -0.15579363],
       [ 2.09104262, -0.22858983,  0.33689437,  0.15224247, -0.81197835,
        -0.39182035, -0.05093854, -1.34625795,  1.16938048,  0.40703022],
       [-0.28354729,  2.33210053,  1.49094796, -0.09068253,  1.94970117,
         0.40549304,  0.92225761,  1.10938147,  2.11342327, -1.10974529],
       [-2.57878551, -0.53999914,  0.2332101 ,  0.37152554,  0.44230151,
        -0.74209667,  0.30774305, -0.07844918,  0.55100758, -0.51487314],
       [ 0.42344986, -1.17024721,  1.67196763,  2.79428322, -0.20551525,
        -0.87967748, -1.26731071,  0.1913228 ,  0.10360225, -0.12734586],
       [ 0.19867409,  0.27057566, -0.32522606, -1.26842456, -0.65854316,
        -0.42967434, -0.96166985, -2.02417278

In [67]:
ran_value_array.max() #give us max value among random values array

2.7942832200080097

In [68]:
ran_value_array.min() #give us min value among random values array

-2.5787855065042677

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [74]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
a[a == b] # find the common items between a & b arrays 

array([2, 2, 4, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [76]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
c = np.where(a==b) # this cmd used to find the positions of matched element at a & b 
c

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [78]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data[names!='Will'] #Find all the values from array data where the values from array names are not equal to Will

array([[-0.28892844, -1.40499742, -1.26465461,  0.67623345],
       [-0.26686603, -1.23580677,  0.84821582,  1.73155748],
       [-0.40836418, -0.70022217,  0.07316138,  1.78845805],
       [ 2.23438561, -0.77804571, -0.72330361,  1.12468657],
       [-0.5095188 , -0.88387101,  0.8190615 ,  0.88011701]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [82]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
result = (names!='Will') & (names!='Joe') #Find all the values from array data where the values from array names are not equal to Will and Joe
data[result]

array([[ 1.66070048,  1.3323998 , -0.25875272, -2.10642623],
       [-1.01252556,  1.45041185, -0.08317856,  0.94172712]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [83]:
array_2d = np.random.randint(low=1,high=15,size=(5,3))
array_2d

array([[ 1,  8,  8],
       [ 4,  1, 10],
       [ 5,  3,  4],
       [12, 11, 13],
       [ 1,  2, 12]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [84]:
array_shape = np.random.randint(low=1,high=16,size=(2,2,4)) # Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16
array_shape 

array([[[ 7, 12,  9,  9],
        [10,  7, 11, 13]],

       [[ 6,  8, 13, 11],
        [ 5,  1,  5, 12]]])

33. Swap axes of the array you created in Question 32

In [85]:
np.swapaxes(array_shape,0,2) #Swap axes of the array

array([[[ 7,  6],
        [10,  5]],

       [[12,  8],
        [ 7,  1]],

       [[ 9, 13],
        [11,  5]],

       [[ 9, 11],
        [13, 12]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [87]:
array_ten = np.arange(10) # create an array of size 10
array_ten_squared = np.sqrt(array_ten) #find the sqroot of every element
np.where(array_ten_squared<0.5,0,array_ten_squared) # checking the condition
# if the values less than 0.5, replace them with 0

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [94]:
array_one = np.random.randn(12) #Create random arrays of range 12
array_two = np.random.randn(12) #Create random arrays of range 12
maximum = np.maximum(array_one , array_two) #make an array with the maximum values between each element of the two arrays
maximum

array([ 0.19538243,  1.03032363, -0.32367025,  0.43187912, -0.14705133,
        0.17822535,  0.48490145,  2.18279101,  0.31126395,  0.26019913,
        1.8746228 , -0.40058474])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [96]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
unique_names = np.unique(names) #Find the unique names and sort them out!
unique_names

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [105]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
array = np.setdiff1d(a, b)
array

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [110]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
sampleArray[1:-1] # delete column two
sampleArray[:,1][:] = [10,10,10] # insert new column in its deleted column
sampleArray

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [112]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x,y) # dot product of the above two matrix

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [115]:
matrixes = np.random.randn(20) # create a matrix of 20 random variable
commulative_sum = matrixes.cumsum() # find its cumulative sum
commulative_sum

array([-0.32927251,  0.98380191,  1.72281928,  0.70047611, -0.38072828,
        0.51230804, -0.39713748, -1.10764147, -1.04895601, -1.61276012,
        0.252018  , -1.39248801, -0.80409851, -2.71062854, -3.48934644,
       -3.26013248, -0.56673185, -1.74444351, -0.34793327, -0.07244853])